// Generated by Copilot - September 1, 2025 at 3:10 PM

// Environment configuration that works in both Vite and Jest
const getApiUrl = (): string => {
  // In test environment, use a mock URL
  if (typeof process !== 'undefined' && process.env.NODE_ENV === 'test') {
    return 'http://localhost:5147/api';
  }
  
  // Fallback for all environments
  return 'http://localhost:5147/api';
};

export const API_BASE_URL = getApiUrl();
