// Generated by Copilot - September 1, 2025 at 5:08 PM
// Global setup for Playwright tests
import { chromium, FullConfig } from '@playwright/test';

async function globalSetup(_config: FullConfig) {
  console.log('🚀 Starting global setup for NurturePath E2E tests...');
  
  // Create a browser instance to verify the test environment
  const browser = await chromium.launch();
  const page = await browser.newPage();
  
  try {
    // Verify the application is accessible
    console.log('🌐 Verifying application accessibility...');
    await page.goto('https://nuturepath.netlify.app/', { 
      waitUntil: 'networkidle',
      timeout: 60000 
    });
    
    // Check if the page loaded successfully
    const title = await page.title();
    console.log(`✅ Application accessible - Page title: ${title}`);
    
    // Verify login page is accessible
    await page.goto('https://nuturepath.netlify.app/login', {
      waitUntil: 'networkidle',
      timeout: 30000
    });
    
    // Check for login form elements
    const emailInput = await page.locator('input[name="emailOrUsername"]').count();
    const passwordInput = await page.locator('input[name="password"]').count();
    const submitButton = await page.locator('button[type="submit"]').count();
    
    if (emailInput > 0 && passwordInput > 0 && submitButton > 0) {
      console.log('✅ Login page elements verified');
    } else {
      console.warn('⚠️ Some login page elements may not be available');
    }
    
  } catch (error) {
    console.error('❌ Global setup failed:', error);
    throw error;
  } finally {
    await browser.close();
  }
  
  console.log('✅ Global setup completed successfully');
}

export default globalSetup;
