// Generated by Copilot - September 1, 2025 at 5:08 PM
// Global teardown for Playwright tests

async function globalTeardown() {
  console.log('🧹 Starting global teardown for NurturePath E2E tests...');
  
  // Cleanup tasks can be added here if needed
  // For example: clearing test data, stopping services, etc.
  
  console.log('✅ Global teardown completed');
}

export default globalTeardown;
