// Generated by Copilot - September 1, 2025 at 12:00 PM
using System.ComponentModel.DataAnnotations;
using ServerApp.Data.Models;

namespace ServerApp.Data.DTOs
{
    /// <summary>
    /// DTO for sending a new message
    /// </summary>
    public class SendMessageRequest
    {
        [Required(ErrorMessage = "Receiver ID is required")]
        public int ReceiverId { get; set; }

        [Required(ErrorMessage = "Subject is required")]
        [StringLength(200, ErrorMessage = "Subject cannot exceed 200 characters")]
        public string Subject { get; set; } = string.Empty;

        [Required(ErrorMessage = "Message content is required")]
        [StringLength(5000, ErrorMessage = "Message content cannot exceed 5000 characters")]
        public string Content { get; set; } = string.Empty;

        public MessagePriority Priority { get; set; } = MessagePriority.Normal;

        public string? ThreadId { get; set; }

        public int? ReplyToMessageId { get; set; }
    }

    /// <summary>
    /// DTO for message response data
    /// </summary>
    public class MessageResponse
    {
        public int Id { get; set; }
        public int SenderId { get; set; }
        public string SenderName { get; set; } = string.Empty;
        public int ReceiverId { get; set; }
        public string ReceiverName { get; set; } = string.Empty;
        public string Subject { get; set; } = string.Empty;
        public string Content { get; set; } = string.Empty;
        public MessagePriority Priority { get; set; }
        public MessageType MessageType { get; set; }
        public bool IsRead { get; set; }
        public DateTime? ReadAt { get; set; }
        public string? ThreadId { get; set; }
        public int? ReplyToMessageId { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
        public List<MessageAttachmentResponse> Attachments { get; set; } = new List<MessageAttachmentResponse>();
    }

    /// <summary>
    /// DTO for message attachment data
    /// </summary>
    public class MessageAttachmentResponse
    {
        public int Id { get; set; }
        public string FileName { get; set; } = string.Empty;
        public long FileSize { get; set; }
        public string ContentType { get; set; } = string.Empty;
        public DateTime UploadedAt { get; set; }
    }

    /// <summary>
    /// DTO for conversation/thread summary
    /// </summary>
    public class ConversationResponse
    {
        public string ThreadId { get; set; } = string.Empty;
        public int OtherUserId { get; set; }
        public string OtherUserName { get; set; } = string.Empty;
        public UserRole OtherUserRole { get; set; }
        public string LastMessageSubject { get; set; } = string.Empty;
        public string LastMessagePreview { get; set; } = string.Empty;
        public DateTime LastMessageAt { get; set; }
        public int UnreadCount { get; set; }
        public MessagePriority HighestPriority { get; set; }
    }

    /// <summary>
    /// DTO for user contact information
    /// </summary>
    public class ContactResponse
    {
        public int Id { get; set; }
        public string FullName { get; set; } = string.Empty;
        public string Email { get; set; } = string.Empty;
        public UserRole Role { get; set; }
        public bool IsActive { get; set; }
        public string? RelationshipType { get; set; }
    }
}
