// Generated by Copilot - September 1, 2025 at 12:00 PM
using System.ComponentModel.DataAnnotations;

namespace ServerApp.Data.DTOs
{
    /// <summary>
    /// Data transfer object for user login with email or username support
    /// </summary>
    public class UserForLoginDto
    {
        [Required(ErrorMessage = "Email or username is required")]
        public string EmailOrUsername { get; set; } = string.Empty;

        [Required(ErrorMessage = "Password is required")]
        public string Password { get; set; } = string.Empty;
        
        // Legacy support
        public string? Username { get; set; }
    }
}
