-- SQL script to add test contacts for messaging
-- Generated by Copilot - September 1, 2025 at 1:15 PM

-- First, let's check what users already exist
-- SELECT * FROM "Users";

-- Add a test Provider user
INSERT INTO "Users" (
    "Email", 
    "Username", 
    "FirstName", 
    "LastName", 
    "Role", 
    "PasswordHash", 
    "PasswordSalt", 
    "IsActive", 
    "CreatedAt", 
    "UpdatedAt"
) VALUES (
    'dr.smith@hospital.com',
    'dr.smith',
    'Dr. Sarah',
    'Smith',
    1, -- Provider role (assuming 1 = Provider based on enum)
    decode('5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8', 'hex'), -- dummy password hash
    decode('73616c74', 'hex'), -- dummy salt
    true,
    NOW(),
    NOW()
);

-- Add a test Family member user
INSERT INTO "Users" (
    "Email", 
    "Username", 
    "FirstName", 
    "LastName", 
    "Role", 
    "PasswordHash", 
    "PasswordSalt", 
    "IsActive", 
    "CreatedAt", 
    "UpdatedAt"
) VALUES (
    'john.doe@family.com',
    'john.doe',
    'John',
    'Doe',
    2, -- Family role (assuming 2 = Family based on enum)
    decode('5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8', 'hex'), -- dummy password hash
    decode('73616c74', 'hex'), -- dummy salt
    true,
    NOW(),
    NOW()
);

-- Get the user IDs for creating relationships
-- You'll need to replace USER_ID with your actual user ID
-- You can find your user ID by running: SELECT "Id", "Email", "FirstName", "LastName" FROM "Users" WHERE "Email" = 'your@email.com';

-- Assuming your user is a Patient (role 0), create a Provider relationship
-- Replace 1 with your actual user ID
INSERT INTO "PatientProviderRelationships" (
    "PatientId",
    "ProviderId", 
    "RelationshipType",
    "IsActive",
    "CreatedAt",
    "CreatedBy"
) VALUES (
    1, -- Replace with your user ID
    (SELECT "Id" FROM "Users" WHERE "Email" = 'dr.smith@hospital.com'),
    'Primary Care Provider',
    true,
    NOW(),
    1 -- Replace with your user ID
);

-- Create a Family access relationship
-- Replace 1 with your actual user ID
INSERT INTO "FamilyAccesses" (
    "PatientId",
    "FamilyMemberId",
    "AccessLevel",
    "IsActive",
    "GrantedAt",
    "GrantedBy"
) VALUES (
    1, -- Replace with your user ID (the patient)
    (SELECT "Id" FROM "Users" WHERE "Email" = 'john.doe@family.com'),
    'Full Access',
    true,
    NOW(),
    1 -- Replace with your user ID
);

-- Verify the relationships were created
SELECT 
    u1."FirstName" || ' ' || u1."LastName" as "Patient",
    u2."FirstName" || ' ' || u2."LastName" as "Provider",
    ppr."RelationshipType"
FROM "PatientProviderRelationships" ppr
JOIN "Users" u1 ON ppr."PatientId" = u1."Id"
JOIN "Users" u2 ON ppr."ProviderId" = u2."Id"
WHERE ppr."IsActive" = true;

SELECT 
    u1."FirstName" || ' ' || u1."LastName" as "Patient",
    u2."FirstName" || ' ' || u2."LastName" as "Family Member",
    fa."AccessLevel"
FROM "FamilyAccesses" fa
JOIN "Users" u1 ON fa."PatientId" = u1."Id"
JOIN "Users" u2 ON fa."FamilyMemberId" = u2."Id"
WHERE fa."IsActive" = true;
