CREATE TABLE "Todos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Todos" PRIMARY KEY ("Id")
);


CREATE TABLE "UserGroups" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "GroupName" text,
    CONSTRAINT "PK_UserGroups" PRIMARY KEY ("Id")
);


CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Email" character varying(255) NOT NULL,
    "Username" text,
    "PasswordHash" bytea NOT NULL,
    "PasswordSalt" bytea NOT NULL,
    "FirstName" character varying(50) NOT NULL,
    "LastName" character varying(50) NOT NULL,
    "Role" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "UserGroupId" integer,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Users_UserGroups_UserGroupId" FOREIGN KEY ("UserGroupId") REFERENCES "UserGroups" ("Id")
);


CREATE TABLE "FamilyAccesses" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PatientId" integer NOT NULL,
    "FamilyMemberId" integer NOT NULL,
    "AccessLevel" integer NOT NULL,
    "CanViewMessages" boolean NOT NULL,
    "CanViewAppointments" boolean NOT NULL,
    "ConsentGivenAt" timestamp with time zone NOT NULL,
    "ConsentExpiresAt" timestamp with time zone,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_FamilyAccesses" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_FamilyAccesses_Users_FamilyMemberId" FOREIGN KEY ("FamilyMemberId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_FamilyAccesses_Users_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "Messages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SenderId" integer NOT NULL,
    "ReceiverId" integer NOT NULL,
    "Subject" character varying(200) NOT NULL,
    "Content" text NOT NULL,
    "Priority" integer NOT NULL,
    "MessageType" integer NOT NULL,
    "IsRead" boolean NOT NULL,
    "ReadAt" timestamp with time zone,
    "IsArchived" boolean NOT NULL,
    "ThreadId" text,
    "ReplyToMessageId" integer,
    "SentAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Messages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Messages_Messages_ReplyToMessageId" FOREIGN KEY ("ReplyToMessageId") REFERENCES "Messages" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Messages_Users_ReceiverId" FOREIGN KEY ("ReceiverId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Messages_Users_SenderId" FOREIGN KEY ("SenderId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "PatientProviderRelationships" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PatientId" integer NOT NULL,
    "ProviderId" integer NOT NULL,
    "RelationshipType" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PatientProviderRelationships" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PatientProviderRelationships_Users_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_PatientProviderRelationships_Users_ProviderId" FOREIGN KEY ("ProviderId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "MessageAttachments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MessageId" integer NOT NULL,
    "FileName" text NOT NULL,
    "FileSize" bigint NOT NULL,
    "FileType" text NOT NULL,
    "FileContent" bytea,
    "FilePath" text,
    "UploadedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_MessageAttachments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MessageAttachments_Messages_MessageId" FOREIGN KEY ("MessageId") REFERENCES "Messages" ("Id") ON DELETE CASCADE
);


CREATE TABLE "MessageReadStatuses" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MessageId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "ReadAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_MessageReadStatuses" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MessageReadStatuses_Messages_MessageId" FOREIGN KEY ("MessageId") REFERENCES "Messages" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MessageReadStatuses_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);


CREATE INDEX "IX_FamilyAccesses_FamilyMemberId" ON "FamilyAccesses" ("FamilyMemberId");


CREATE INDEX "IX_FamilyAccesses_PatientId" ON "FamilyAccesses" ("PatientId");


CREATE INDEX "IX_MessageAttachments_MessageId" ON "MessageAttachments" ("MessageId");


CREATE UNIQUE INDEX "IX_MessageReadStatuses_MessageId_UserId" ON "MessageReadStatuses" ("MessageId", "UserId");


CREATE INDEX "IX_MessageReadStatuses_UserId" ON "MessageReadStatuses" ("UserId");


CREATE INDEX "IX_Messages_ReceiverId" ON "Messages" ("ReceiverId");


CREATE INDEX "IX_Messages_ReplyToMessageId" ON "Messages" ("ReplyToMessageId");


CREATE INDEX "IX_Messages_SenderId" ON "Messages" ("SenderId");


CREATE UNIQUE INDEX "IX_PatientProviderRelationships_PatientId_ProviderId_Relations~" ON "PatientProviderRelationships" ("PatientId", "ProviderId", "RelationshipType");


CREATE INDEX "IX_PatientProviderRelationships_ProviderId" ON "PatientProviderRelationships" ("ProviderId");


CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");


CREATE INDEX "IX_Users_UserGroupId" ON "Users" ("UserGroupId");


