// Generated by Copilot - September 1, 2025 at 3:10 PM
import { render, screen } from '@testing-library/react';
import Card, { CardContent, CardHeader } from '../Card';

describe('Card Component', () => {
  it('should render card with children', () => {
    render(
      <Card>
        <div>Card content</div>
      </Card>
    );
    expect(screen.getByText('Card content')).toBeInTheDocument();
  });

  it('should apply custom className', () => {
    render(<Card className="custom-card">Content</Card>);
    const cardElement = screen.getByText('Content').closest('div');
    expect(cardElement).toHaveClass('custom-card');
  });

  it('should render CardHeader with title', () => {
    render(
      <Card>
        <CardHeader>
          <h2>Card Title</h2>
        </CardHeader>
      </Card>
    );
    expect(screen.getByText('Card Title')).toBeInTheDocument();
  });

  it('should render CardContent with body', () => {
    render(
      <Card>
        <CardContent>
          <p>Card body content</p>
        </CardContent>
      </Card>
    );
    expect(screen.getByText('Card body content')).toBeInTheDocument();
  });

  it('should render complete card structure', () => {
    render(
      <Card>
        <CardHeader>
          <h2>Title</h2>
        </CardHeader>
        <CardContent>
          <p>Content</p>
        </CardContent>
      </Card>
    );
    
    expect(screen.getByText('Title')).toBeInTheDocument();
    expect(screen.getByText('Content')).toBeInTheDocument();
  });

  it('should apply custom className to CardHeader', () => {
    render(
      <CardHeader className="custom-header">
        <h2>Header</h2>
      </CardHeader>
    );
    expect(screen.getByText('Header').parentElement).toHaveClass('custom-header');
  });

  it('should apply custom className to CardContent', () => {
    render(
      <CardContent className="custom-content">
        <p>Content</p>
      </CardContent>
    );
    expect(screen.getByText('Content').parentElement).toHaveClass('custom-content');
  });
});
