// Generated by Copilot - September 1, 2025 at 1:25 PM
using System.Text.Json.Serialization;

namespace ServerApp.Data.Models
{
    /// <summary>
    /// Represents a care task assigned to a patient or provider
    /// </summary>
    public class CareTask
    {
        public int Id { get; set; }
        
        /// <summary>
        /// Patient this task relates to
        /// </summary>
        public int PatientId { get; set; }
        public virtual Patient Patient { get; set; } = null!;
        
        /// <summary>
        /// Title of the task
        /// </summary>
        public string Title { get; set; } = string.Empty;
        
        /// <summary>
        /// Detailed description of the task
        /// </summary>
        public string? Description { get; set; }
        
        /// <summary>
        /// Task status
        /// </summary>
        public TaskStatus Status { get; set; } = TaskStatus.Pending;
        
        /// <summary>
        /// When the task is due
        /// </summary>
        public DateTime? DueDate { get; set; }
        
        /// <summary>
        /// User assigned to complete this task
        /// </summary>
        public int? AssignedToId { get; set; }
        public virtual User? AssignedTo { get; set; }
        
        /// <summary>
        /// User who created this task
        /// </summary>
        public int CreatedById { get; set; }
        public virtual User CreatedBy { get; set; } = null!;
        
        /// <summary>
        /// When the task was created
        /// </summary>
        public DateTime CreatedAt { get; set; }
        
        /// <summary>
        /// When the task was last updated
        /// </summary>
        public DateTime UpdatedAt { get; set; }
        
        /// <summary>
        /// When the task was completed
        /// </summary>
        public DateTime? CompletedAt { get; set; }
        
        /// <summary>
        /// Task priority level
        /// </summary>
        public int Priority { get; set; } = 1;
    }
    
    /// <summary>
    /// Task status enumeration
    /// </summary>
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum TaskStatus
    {
        Pending,
        InProgress,
        Completed,
        Cancelled
    }
}
