// Generated by Copilot - September 1, 2025 at 12:00 PM
namespace ServerApp.Data.Models
{
    /// <summary>
    /// Manages access permissions for family members to patient information
    /// </summary>
    public class FamilyAccess
    {
        public int Id { get; set; }
        
        /// <summary>
        /// ID of the patient granting access
        /// </summary>
        public int PatientId { get; set; }
        
        /// <summary>
        /// ID of the family member being granted access
        /// </summary>
        public int FamilyMemberId { get; set; }
        
        /// <summary>
        /// Level of access granted (Basic or Extended)
        /// </summary>
        public AccessLevel AccessLevel { get; set; }
        
        /// <summary>
        /// Whether family member can view message communications
        /// </summary>
        public bool CanViewMessages { get; set; } = false;
        
        /// <summary>
        /// Whether family member can view appointment information
        /// </summary>
        public bool CanViewAppointments { get; set; } = true;
        
        /// <summary>
        /// When consent was given for this access
        /// </summary>
        public DateTime ConsentGivenAt { get; set; }
        
        /// <summary>
        /// When the consent expires (if applicable)
        /// </summary>
        public DateTime? ConsentExpiresAt { get; set; }
        
        /// <summary>
        /// Whether this access is currently active
        /// </summary>
        public bool IsActive { get; set; } = true;
        
        /// <summary>
        /// When this access record was created
        /// </summary>
        public DateTime CreatedAt { get; set; }
        
        // Navigation properties
        public virtual User Patient { get; set; } = null!;
        public virtual User FamilyMember { get; set; } = null!;
    }
    
    /// <summary>
    /// Levels of access that can be granted to family members
    /// </summary>
    public enum AccessLevel
    {
        /// <summary>
        /// Basic access to general information
        /// </summary>
        Basic = 1,
        
        /// <summary>
        /// Extended access to more detailed information
        /// </summary>
        Extended = 2
    }
}
