// Generated by Copilot - September 1, 2025 at 12:00 PM
namespace ServerApp.Data.Models
{
    /// <summary>
    /// Tracks when messages are read by recipients for audit and notification purposes
    /// </summary>
    public class MessageReadStatus
    {
        public int Id { get; set; }
        
        /// <summary>
        /// ID of the message that was read
        /// </summary>
        public int MessageId { get; set; }
        
        /// <summary>
        /// ID of the user who read the message
        /// </summary>
        public int UserId { get; set; }
        
        /// <summary>
        /// When the message was read
        /// </summary>
        public DateTime ReadAt { get; set; }
        
        // Navigation properties
        public virtual Message Message { get; set; } = null!;
        public virtual User User { get; set; } = null!;
    }
}
