// Generated by Copilot - September 1, 2025 at 12:00 PM
namespace ServerApp.Data.Models
{
    /// <summary>
    /// Represents a file attachment associated with a message
    /// </summary>
    public class MessageAttachment
    {
        public int Id { get; set; }
        
        /// <summary>
        /// ID of the message this attachment belongs to
        /// </summary>
        public int MessageId { get; set; }
        
        /// <summary>
        /// Original filename of the uploaded file
        /// </summary>
        public string FileName { get; set; } = string.Empty;
        
        /// <summary>
        /// Size of the file in bytes
        /// </summary>
        public long FileSize { get; set; }
        
        /// <summary>
        /// MIME type of the file
        /// </summary>
        public string FileType { get; set; } = string.Empty;
        
        /// <summary>
        /// File content stored as binary data (for small files)
        /// </summary>
        public byte[]? FileContent { get; set; }
        
        /// <summary>
        /// Encrypted path where the file is stored (for large files)
        /// </summary>
        public string? FilePath { get; set; }
        
        /// <summary>
        /// When the file was uploaded
        /// </summary>
        public DateTime UploadedAt { get; set; }
        
        // Navigation properties
        public virtual Message Message { get; set; } = null!;
    }
}
