// Generated by Copilot - September 1, 2025 at 1:25 PM
using System.Text.Json.Serialization;

namespace ServerApp.Data.Models
{
    /// <summary>
    /// Represents an alert or notification for a patient
    /// </summary>
    public class PatientAlert
    {
        public int Id { get; set; }
        
        /// <summary>
        /// Patient this alert belongs to
        /// </summary>
        public int PatientId { get; set; }
        public virtual Patient Patient { get; set; } = null!;
        
        /// <summary>
        /// Alert type (critical, warning, info)
        /// </summary>
        public AlertType Type { get; set; }
        
        /// <summary>
        /// Alert message/description
        /// </summary>
        public string Message { get; set; } = string.Empty;
        
        /// <summary>
        /// Whether the alert has been acknowledged
        /// </summary>
        public bool IsAcknowledged { get; set; } = false;
        
        /// <summary>
        /// User who acknowledged the alert
        /// </summary>
        public int? AcknowledgedById { get; set; }
        public virtual User? AcknowledgedBy { get; set; }
        
        /// <summary>
        /// When the alert was acknowledged
        /// </summary>
        public DateTime? AcknowledgedAt { get; set; }
        
        /// <summary>
        /// When the alert was created
        /// </summary>
        public DateTime CreatedAt { get; set; }
        
        /// <summary>
        /// Alert priority level
        /// </summary>
        public int Priority { get; set; } = 1;
    }
    
    /// <summary>
    /// Alert type enumeration
    /// </summary>
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum AlertType
    {
        Info,
        Warning,
        Critical
    }
}
