// Generated by Copilot - September 1, 2025 at 12:00 PM
namespace ServerApp.Data.Models
{
    /// <summary>
    /// Represents the relationship between patients and their healthcare providers
    /// </summary>
    public class PatientProviderRelationship
    {
        public int Id { get; set; }
        
        /// <summary>
        /// ID of the patient in the relationship
        /// </summary>
        public int PatientId { get; set; }
        
        /// <summary>
        /// ID of the provider in the relationship
        /// </summary>
        public int ProviderId { get; set; }
        
        /// <summary>
        /// Type of relationship (Primary, Secondary, Consultant)
        /// </summary>
        public RelationshipType RelationshipType { get; set; }
        
        /// <summary>
        /// Whether this relationship is currently active
        /// </summary>
        public bool IsActive { get; set; } = true;
        
        /// <summary>
        /// When the provider-patient relationship started
        /// </summary>
        public DateTime StartDate { get; set; }
        
        /// <summary>
        /// When the provider-patient relationship ended (if applicable)
        /// </summary>
        public DateTime? EndDate { get; set; }
        
        /// <summary>
        /// When this relationship record was created
        /// </summary>
        public DateTime CreatedAt { get; set; }
        
        // Navigation properties
        public virtual User Patient { get; set; } = null!;
        public virtual User Provider { get; set; } = null!;
    }
    
    /// <summary>
    /// Types of provider-patient relationships
    /// </summary>
    public enum RelationshipType
    {
        /// <summary>
        /// Primary care provider
        /// </summary>
        Primary = 1,
        
        /// <summary>
        /// Secondary care provider
        /// </summary>
        Secondary = 2,
        
        /// <summary>
        /// Consultant/specialist
        /// </summary>
        Consultant = 3
    }
}
