// Generated by Copilot - September 1, 2025 at 12:00 PM
namespace ServerApp.Data.Models
{
    /// <summary>
    /// Represents a user in the healthcare communication system
    /// Supports Patient, Provider, and Family member roles
    /// </summary>
    public class User
    {
        public int Id { get; set; }
        
        /// <summary>
        /// Unique email address for the user
        /// </summary>
        public string Email { get; set; } = string.Empty;
        
        /// <summary>
        /// Legacy username field - will be phased out in favor of email
        /// </summary>
        public string? Username { get; set; }
        
        /// <summary>
        /// Hashed password for authentication
        /// </summary>
        public byte[] PasswordHash { get; set; } = Array.Empty<byte>();
        
        /// <summary>
        /// Salt used for password hashing
        /// </summary>
        public byte[] PasswordSalt { get; set; } = Array.Empty<byte>();
        
        /// <summary>
        /// User's first name
        /// </summary>
        public string FirstName { get; set; } = string.Empty;
        
        /// <summary>
        /// User's last name
        /// </summary>
        public string LastName { get; set; } = string.Empty;
        
        /// <summary>
        /// User's role in the system (Patient, Provider, Family)
        /// </summary>
        public UserRole Role { get; set; }
        
        /// <summary>
        /// Whether the user account is active
        /// </summary>
        public bool IsActive { get; set; } = true;
        
        /// <summary>
        /// When the user account was created
        /// </summary>
        public DateTime CreatedAt { get; set; }
        
        /// <summary>
        /// When the user account was last updated
        /// </summary>
        public DateTime UpdatedAt { get; set; }
        
        // Legacy navigation properties (maintaining for backward compatibility)
        public int? UserGroupId { get; set; } // Foreign key to UserGroup
        public UserGroup? UserGroup { get; set; } // Navigation property to UserGroup
        
        // New navigation properties for messaging system
        public virtual ICollection<Message> SentMessages { get; set; } = new List<Message>();
        public virtual ICollection<Message> ReceivedMessages { get; set; } = new List<Message>();
        public virtual ICollection<PatientProviderRelationship> PatientRelationships { get; set; } = new List<PatientProviderRelationship>();
        public virtual ICollection<PatientProviderRelationship> ProviderRelationships { get; set; } = new List<PatientProviderRelationship>();
        public virtual ICollection<FamilyAccess> PatientFamilyAccess { get; set; } = new List<FamilyAccess>();
        public virtual ICollection<FamilyAccess> FamilyMemberAccess { get; set; } = new List<FamilyAccess>();
    }
    
    /// <summary>
    /// Enumeration for user roles in the healthcare communication system
    /// </summary>
    public enum UserRole
    {
        /// <summary>
        /// Expecting mothers and patients receiving care
        /// </summary>
        Patient = 1,
        
        /// <summary>
        /// Healthcare providers (midwives, doctors, nurses)
        /// </summary>
        Provider = 2,
        
        /// <summary>
        /// Family members with authorized access
        /// </summary>
        Family = 3
    }
}
