// Generated by Copilot on September 1, 2025 at 9:30 AM
import { useContext } from 'react';
import { ThemeContext } from '../contexts/theme';

export const useTheme = () => {
  const context = useContext(ThemeContext);
  if (context === undefined) {
    throw new Error('useTheme must be used within a ThemeProvider');
  }
  return context;
};