// Generated by Copilot on September 1, 2025

namespace ServerApp.Services
{
    /// <summary>
    /// Interface for SMS messaging service using external providers
    /// </summary>
    public interface ISmsService
    {
        /// <summary>
        /// Sends an SMS message to a single recipient
        /// </summary>
        /// <param name="phoneNumber">The recipient's phone number</param>
        /// <param name="message">The message content to send</param>
        /// <returns>Success status and any error messages</returns>
        Task<(bool Success, string ErrorMessage)> SendSmsAsync(string phoneNumber, string message);

        /// <summary>
        /// Sends an SMS message to multiple recipients
        /// </summary>
        /// <param name="phoneNumbers">List of recipient phone numbers</param>
        /// <param name="message">The message content to send</param>
        /// <returns>Results for each recipient</returns>
        Task<List<(string PhoneNumber, bool Success, string ErrorMessage)>> SendSmsToMultipleAsync(List<string> phoneNumbers, string message);
    }
}
